import { test, expect } from './game-harness.js';
const newOnly = info => test.skip(info.project.metadata.target==='legacy','Daily collection is new');
async function clock(page,date='2026-10-03'){const time=new Date(`${date}T04:00:00Z`);await page.clock.install({time:new Date(time.getTime()-60000)});await page.clock.pauseAt(time);}
async function start(page){await page.locator('#dailyOpen').click();await page.locator('#dailyCustomText').fill('cat 猫\ndog 狗');await page.locator('#dailyImport').click();await page.locator('#dailyStart').click();}
async function warm(page){for(const word of ['cat','dog']){await page.keyboard.type(word);await page.locator('#dailyNext').click();}await page.locator('#dailyFormal').click();}

test('actual daily collection finish, visible equipped gift and idempotent reload',async({game,page},info)=>{
 newOnly(info);await clock(page);await game.open();await expect(page.locator('#dailyPartner')).toBeVisible();await expect(page.locator('#dailyPartnerProgress')).toContainText('还差 5 词');await start(page);await warm(page);expect((await game.saved()).dictationMastered).toEqual([]);await page.locator('#dailyHint').click();await page.keyboard.type('cat');await page.locator('#dailyNext').click();await page.keyboard.type('dog');await page.locator('#dailyNext').click();
 await expect(page.locator('#dailyGift')).toContainText('今日外观');const saved=await game.saved();expect(saved.dailyCollection.cosmetics).toHaveLength(1);await page.locator('#dailyGiftEquip').click();await expect(page.locator('#dailyGiftStatus')).toContainText('已穿戴');await page.locator('#dailyDoneHome').click();await expect(page.locator('#dailyCheckin')).toContainText('连续 1 天');await expect(page.locator('#dailyPartnerProgress')).toContainText('还差 4 词');
 await page.locator('#dailyAtlasToggle').click();await page.locator('#dailyAtlasUnit').selectOption('0');await expect(page.locator('#dailyAtlasCards')).toContainText('cat');await expect(page.locator('#dailyAtlasCards [data-word="cat"]')).toContainText('练过');await expect(page.locator('#dailyAtlasCards [data-word="dog"]')).toContainText('默写对');const before=(await game.saved()).dailyCollection;
 const frame=before.equipped.frame;if(frame){await expect(page.locator(`#dailyAtlasCards [data-frame="${frame}"]`)).toHaveCount(2);expect(await page.locator('#dailyAtlasCards .daily-card').first().evaluate(n=>getComputedStyle(n).boxShadow)).not.toBe('none');}else await expect(page.locator('#dailyPartner [data-accessory]')).toBeVisible();
 await game.reload();expect((await game.saved()).dailyCollection).toEqual(before);if(frame)await expect(page.locator('#dailyCardFrame')).toHaveValue(frame);else await expect(page.locator('#dailyPartner [data-accessory]')).toBeVisible();
});
for(const width of [320,390])test(`original partner and all atlas cards fit ${width}px and never cover dictation`,async({game,page},info)=>{
 newOnly(info);await page.setViewportSize({width,height:844});await clock(page);await game.open();await expect(page.locator('#dailyPartner')).toBeVisible();await page.locator('#dailyAtlasToggle').click();await expect(page.locator('#dailyAtlasCards .daily-card')).toHaveCount(45);
 const bounds=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,viewport:innerWidth,partner:document.querySelector('#dailyPartner').getBoundingClientRect().toJSON(),cards:[...document.querySelectorAll('#dailyAtlasCards .daily-card')].map(n=>n.getBoundingClientRect().toJSON())}));expect(bounds.scroll).toBeLessThanOrEqual(width);expect(bounds.partner.right).toBeLessThanOrEqual(width);for(const card of bounds.cards){expect(card.left).toBeGreaterThanOrEqual(0);expect(card.right).toBeLessThanOrEqual(width);}
 await start(page);await warm(page);await expect(page.locator('#dailyInput')).toBeVisible();await expect(page.locator('#dailyKeys')).toBeVisible();await expect(page.locator('#dailyPartner')).not.toBeVisible();await expect(page.locator('#dailyAtlasCards')).not.toBeVisible();const layout=await page.evaluate(()=>{const input=document.querySelector('#dailyInput').getBoundingClientRect(),keys=document.querySelector('#dailyKeys').getBoundingClientRect();return {inputBottom:input.bottom,keysTop:keys.top,right:keys.right,scroll:document.documentElement.scrollWidth};});expect(layout.keysTop).toBeGreaterThanOrEqual(layout.inputBottom);expect(layout.right).toBeLessThanOrEqual(width);expect(layout.scroll).toBeLessThanOrEqual(width);
});
test('custom snapshot text is rendered safely and original collection is separate from report',async({game,page},info)=>{
 newOnly(info);await clock(page);await game.open({saved:{wordExposure:{unsafe:{word:{w:'<img src=x onerror=alert(1)>',z:'<script>window.bad=1</script>'},seen:true,practiced:true}}}});await page.locator('#dailyAtlasToggle').click();await page.locator('#dailyAtlasUnit').selectOption('0');await expect(page.locator('#dailyAtlasCards')).toContainText('<img src=x onerror=alert(1)>');await expect(page.locator('#dailyAtlasCards img')).toHaveCount(0);await expect(page.locator('#dailyAtlasCards script')).toHaveCount(0);expect(await page.evaluate(()=>window.bad)).toBeUndefined();
 const order=await page.evaluate(()=>[...document.querySelector('#dailyEntry').children].filter(n=>n.id).map(n=>n.id));expect(order.indexOf('dailyCollectionHost')).toBeLessThan(order.indexOf('dailyHomeReport'));expect(await page.evaluate(()=>document.querySelector('#dailyEntry').compareDocumentPosition(document.querySelector('#keyboardTipHost'))&Node.DOCUMENT_POSITION_FOLLOWING)).toBeTruthy();
});
test('owned partner decorations are selectable and a guaranteed new frame visibly decorates cards',async({game,page},info)=>{
 newOnly(info);await clock(page);await game.open({saved:{dailyCollection:{cosmetics:['leaf-ribbon','sky-scarf','star-pin'],unknown:'keep'}}});
 await page.locator('#dailyAccessory').selectOption('sky-scarf');await expect(page.locator('#dailyPartner [data-accessory="sky-scarf"]')).toBeVisible();await page.locator('#dailyAccessory').selectOption('star-pin');await expect(page.locator('#dailyPartner [data-accessory="star-pin"]')).toBeVisible();await start(page);await warm(page);for(const word of ['cat','dog']){await page.keyboard.type(word);await page.locator('#dailyNext').click();}
 await expect(page.locator('#dailyGift')).toContainText('卡框');await page.locator('#dailyGiftEquip').click();await page.locator('#dailyDoneHome').click();await page.locator('#dailyAtlasToggle').click();await page.locator('#dailyAtlasUnit').selectOption('0');const saved=await game.saved(),frame=saved.dailyCollection.equipped.frame;expect(frame).toMatch(/-frame$/);await expect(page.locator('#dailyCardFrame')).toHaveValue(frame);await expect(page.locator(`#dailyAtlasCards [data-frame="${frame}"]`)).toHaveCount(2);expect(saved.dailyCollection.unknown).toBe('keep');
});
test('blank exit gets no gift or sign and real makeup does not fabricate practice',async({game,page},info)=>{
 newOnly(info);await clock(page,'2026-10-04');await game.open({saved:{dailyCollection:{checkins:{'2026-10-01':'practice','2026-10-03':'practice'},cosmetics:['leaf-ribbon']}}});
 const before=(await game.saved()).dailyReports;await page.locator('#dailyMakeupDate').selectOption('2026-10-02');await page.locator('#dailyMakeup').click();await expect(page.locator('#dailyMakeupStatus')).toContainText('已补签 2026-10-02');await expect(page.locator('#dailyCheckin')).toContainText('连续 3 天');await expect(page.locator('#dailyMakeup')).toHaveCount(0);expect((await game.saved()).dailyReports).toEqual(before);await expect(page.locator('#dailyReportWords')).toContainText('0');
 await start(page);await page.locator('#dailyPause').click();await page.locator('#dailyFinish').click();await expect(page.locator('#dailyGiftEquip')).toHaveCount(0);expect((await game.saved()).dailyCollection.cosmetics).toEqual(['leaf-ribbon']);await page.locator('#dailyDoneHome').click();await expect(page.locator('#dailyCheckin')).toContainText('今日练习后结束即可打卡');
});
test('actual cosmetic storage rejection shows current outfit and honest unsaved notice while dictation works',async({game,page},info)=>{
 newOnly(info);await clock(page);await game.open({saved:{dailyCollection:{cosmetics:['leaf-ribbon']}}});
 await page.evaluate(()=>{Storage.prototype.setItem=function(){throw new DOMException('blocked','QuotaExceededError');};});await page.locator('#dailyAccessory').selectOption('leaf-ribbon');await expect(page.locator('#dailyPartner [data-accessory="leaf-ribbon"]')).toBeVisible();await expect(page.locator('#dailyCollectionSaveWarning')).toContainText('未保存');expect((await game.saved()).dailyCollection.equipped.partner).not.toBe('leaf-ribbon');
 await start(page);await warm(page);await page.keyboard.type('cat');await expect(page.locator('#dailyInput')).toHaveText('cat');await expect(page.locator('#dailySaveWarning')).toBeVisible();
});
