import { test, expect } from './game-harness.js';
const newOnly = info => test.skip(info.project.metadata.target==='legacy','Daily collection is new');
async function clock(page){await page.clock.install({time:new Date('2026-10-03T03:59:00Z')});await page.clock.pauseAt(new Date('2026-10-03T04:00:00Z'));}
async function start(page){await page.locator('#dailyOpen').click();await page.locator('#dailyCustomText').fill('cat 猫\ndog 狗');await page.locator('#dailyImport').click();await page.locator('#dailyStart').click();}
async function warm(page){for(const word of ['cat','dog']){await page.keyboard.type(word);await page.locator('#dailyNext').click();}await page.locator('#dailyFormal').click();}

test('actual daily collection finish, visible equipped gift and idempotent reload',async({game,page},info)=>{
 newOnly(info);await clock(page);await game.open();await expect(page.locator('#dailyPartner')).toBeVisible();await expect(page.locator('#dailyPartnerProgress')).toContainText('还差 5 词');await start(page);await warm(page);expect((await game.saved()).dictationMastered).toEqual([]);await page.locator('#dailyHint').click();await page.keyboard.type('cat');await page.locator('#dailyNext').click();await page.keyboard.type('dog');await page.locator('#dailyNext').click();
 await expect(page.locator('#dailyGift')).toContainText('今日外观');const saved=await game.saved();expect(saved.dailyCollection.cosmetics).toHaveLength(1);await page.locator('#dailyGiftEquip').click();await expect(page.locator('#dailyGiftStatus')).toContainText('已穿戴');await page.locator('#dailyDoneHome').click();await expect(page.locator('#dailyCheckin')).toContainText('连续 1 天');await expect(page.locator('#dailyPartnerProgress')).toContainText('还差 4 词');await expect(page.locator('#dailyPartner [data-accessory]')).toBeVisible();
 await page.locator('#dailyAtlasToggle').click();await page.locator('#dailyAtlasUnit').selectOption('0');await expect(page.locator('#dailyAtlasCards')).toContainText('cat');await expect(page.locator('#dailyAtlasCards [data-word="cat"]')).toContainText('练过');await expect(page.locator('#dailyAtlasCards [data-word="dog"]')).toContainText('默写对');const before=(await game.saved()).dailyCollection;await game.reload();expect((await game.saved()).dailyCollection).toEqual(before);await expect(page.locator('#dailyPartner [data-accessory]')).toBeVisible();
});
for(const width of [320,390])test(`original partner and all atlas cards fit ${width}px and never cover dictation`,async({game,page},info)=>{
 newOnly(info);await page.setViewportSize({width,height:844});await clock(page);await game.open();await expect(page.locator('#dailyPartner')).toBeVisible();await page.locator('#dailyAtlasToggle').click();await expect(page.locator('#dailyAtlasCards .daily-card')).toHaveCount(44);
 const bounds=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,viewport:innerWidth,partner:document.querySelector('#dailyPartner').getBoundingClientRect().toJSON(),cards:[...document.querySelectorAll('#dailyAtlasCards .daily-card')].map(n=>n.getBoundingClientRect().toJSON())}));expect(bounds.scroll).toBeLessThanOrEqual(width);expect(bounds.partner.right).toBeLessThanOrEqual(width);for(const card of bounds.cards){expect(card.left).toBeGreaterThanOrEqual(0);expect(card.right).toBeLessThanOrEqual(width);}
 await start(page);await warm(page);await expect(page.locator('#dailyInput')).toBeVisible();await expect(page.locator('#dailyKeys')).toBeVisible();await expect(page.locator('#dailyPartner')).not.toBeVisible();await expect(page.locator('#dailyAtlasCards')).not.toBeVisible();const layout=await page.evaluate(()=>{const input=document.querySelector('#dailyInput').getBoundingClientRect(),keys=document.querySelector('#dailyKeys').getBoundingClientRect();return {inputBottom:input.bottom,keysTop:keys.top,right:keys.right,scroll:document.documentElement.scrollWidth};});expect(layout.keysTop).toBeGreaterThanOrEqual(layout.inputBottom);expect(layout.right).toBeLessThanOrEqual(width);expect(layout.scroll).toBeLessThanOrEqual(width);
});
test('custom snapshot text is rendered safely and original collection is separate from report',async({game,page},info)=>{
 newOnly(info);await clock(page);await game.open({saved:{wordExposure:{unsafe:{word:{w:'<img src=x onerror=alert(1)>',z:'<script>window.bad=1</script>'},seen:true,practiced:true}}}});await page.locator('#dailyAtlasToggle').click();await page.locator('#dailyAtlasUnit').selectOption('0');await expect(page.locator('#dailyAtlasCards')).toContainText('<img src=x onerror=alert(1)>');await expect(page.locator('#dailyAtlasCards img')).toHaveCount(0);await expect(page.locator('#dailyAtlasCards script')).toHaveCount(0);expect(await page.evaluate(()=>window.bad)).toBeUndefined();
 const order=await page.evaluate(()=>[...document.querySelector('#dailyEntry').children].filter(n=>n.id).map(n=>n.id));expect(order.indexOf('dailyCollectionHost')).toBeLessThan(order.indexOf('dailyHomeReport'));expect(await page.evaluate(()=>document.querySelector('#dailyEntry').compareDocumentPosition(document.querySelector('#keyboardTipHost'))&Node.DOCUMENT_POSITION_FOLLOWING)).toBeTruthy();
});
