import test from 'node:test';
import assert from 'node:assert/strict';
const cat={w:'cat',z:'猫'}, dog={w:'dog',z:'狗'}, phrase={w:"look after one's self",z:'照顾自己'};
const load=()=>import('../../src/domain/daily-session.js');
const app=()=>import('../../src/app/daily-dictation.js');
async function setup(words=[cat,dog], extras={}){
  const {createDailyDictationController}=await app(); let clock=1000;let saves=0;let changes=0;
  const db={mastered:[],dictationMastered:[],reviewQueue:[],future:{keep:1}};
  const c=createDailyDictationController({getDB:()=>db,getWords:()=>words,now:()=>clock,random:()=>0.4,
    persist:()=>{saves++;return true},onChange:()=>changes++, ...extras});
  return {c,db,advance:n=>clock+=n,saves:()=>saves,changes:()=>changes};
}
function spell(c,text){ for(const ch of text)c.input(ch); }
function warm(c,words){for(const w of words){spell(c,w.w.replace(/[^a-z]/g,''));c.next();}c.beginFormal();}

test('daily selection is bounded16 and reports unselected textbook words',async()=>{const {selectDailyWords}=await load();const words=Array.from({length:45},(_,i)=>({w:'word'+i,z:'词'}));const x=selectDailyWords({words});assert.equal(x.words.length,16);assert.equal(x.remaining,29);});
test('due reviews take at most half and never duplicate today words',async()=>{const {selectDailyWords}=await load();const words=[cat,dog,{w:'pig',z:'猪'},{w:'hen',z:'鸡'}];const due=[cat,dog,{w:'fox',z:'狐'},{w:'owl',z:'鸮'}];const x=selectDailyWords({words,dueWords:due,limit:4});assert.equal(x.reviewCount,2);assert.equal(new Set(x.words.map(x=>x.w)).size,4);assert.equal(x.words.length,4);});
test('oneword pool does not become all-review',async()=>{const {selectDailyWords}=await load();const x=selectDailyWords({words:[cat],dueWords:[dog],limit:1});assert.deepEqual(x.words,[cat]);assert.equal(x.reviewCount,0);});
test('rotation prioritizes new/remaining words before mastered',async()=>{const {selectDailyWords}=await load();const words=Array.from({length:20},(_,i)=>({w:'w'+i,z:'词'}));const first=selectDailyWords({words,limit:4});const second=selectDailyWords({words,limit:4,cursor:first.nextCursor});assert.deepEqual(second.words,words.slice(4,8));const fresh=selectDailyWords({words,limit:4,mastered:words.slice(0,16).map(w=>w.w)});assert.deepEqual(fresh.words,words.slice(16));});
test('encounters partition into3 regular and1 boss without unlimited battles',async()=>{const {dailyEncounters}=await load();const x=dailyEncounters(16);assert.deepEqual(x.map(x=>x.count),[4,4,4,4]);assert.equal(x.filter(x=>x.boss).length,1);assert.equal(x.at(-1).boss,true);assert.equal(dailyEncounters(2).length,2);});
test('warmup completes each selected word once and never formalcredits',async()=>{const {c,db}=await setup();assert.equal(c.start({mode:'dictation',unit:6}),true);warm(c,[cat,dog]);assert.equal(c.state().phase,'formal');assert.deepEqual(db.dictationMastered,[]);assert.deepEqual(db.mastered,['cat','dog']);assert.deepEqual(c.state().warmupDone,['cat','dog']);});
test('formal starts explicitly afterwarmup and has no implicit transition',async()=>{const {c}=await setup([cat]);c.start({mode:'dictation',unit:1});spell(c,'cat');c.next();assert.equal(c.state().phase,'formal-ready');assert.equal(c.input('c'),false);c.beginFormal();assert.equal(c.state().attempt.phase,'formal');});
test('complete clean formal wordcredits once and ends with honest summary',async()=>{const {c,db}=await setup([cat]);c.start({mode:'dictation',unit:1});warm(c,[cat]);spell(c,'cat');spell(c,'cat');assert.deepEqual(db.dictationMastered,['cat']);assert.equal(c.state().results.length,1);c.next();assert.equal(c.state().phase,'completed');assert.equal(c.summary().completed,1);assert.equal(c.summary().firstTry,1);assert.equal(c.input('c'),false);assert.equal(c.next(),false);});
test('wrongorder isreview immediately even when session pausedunfinished',async()=>{const {c,db}=await setup([cat]);c.start({mode:'dictation',unit:1});warm(c,[cat]);c.input('a');assert.equal(c.state().attempt.feedback,'不对');assert.deepEqual(db.reviewQueue,['cat']);c.pause();assert.deepEqual(db.dictationMastered,[]);});
test('wrongletter corrected still notmastered and retainedreview',async()=>{const {c,db}=await setup([cat]);c.start({mode:'dictation',unit:1});warm(c,[cat]);c.input('z');spell(c,'cat');c.next();assert.deepEqual(db.dictationMastered,[]);assert.deepEqual(db.reviewQueue,['cat']);assert.equal(c.summary().firstTry,0);assert.equal(c.summary().wrong[0].z,'猫');});
test('hint marks evidence before answer andqueues partial word',async()=>{const {c,db}=await setup([cat]);c.start({mode:'dictation',unit:1});warm(c,[cat]);assert.equal(c.hint(),'c');assert.equal(c.state().attempt.hints,1);assert.deepEqual(db.reviewQueue,['cat']);spell(c,'cat');c.next();assert.deepEqual(db.dictationMastered,[]);});
test('reveals prophecyandvision each make formal reviewonly',async()=>{for(const kind of ['prophecy','vision']){const {c,db}=await setup([cat]);c.start({mode:'dictation',unit:1});warm(c,[cat]);c.assist(kind);spell(c,'cat');c.next();assert.deepEqual(db.dictationMastered,[]);assert.deepEqual(db.reviewQueue,['cat']);}});
test('paused input,hints,nextand stale click are inert',async()=>{const {c,db,saves}=await setup([cat]);c.start({mode:'dictation',unit:1});warm(c,[cat]);c.pause();const before=JSON.stringify(db),n=saves();assert.equal(c.input('c'),false);assert.equal(c.hint(),false);assert.equal(c.next(),false);assert.equal(JSON.stringify(db),before);assert.equal(saves(),n);});
test('save reload ispaused and resumes exact inputwithout duplicatecredit',async()=>{const {c,db}=await setup([cat]);c.start({mode:'dictation',unit:1});warm(c,[cat]);c.input('c');c.pause();const raw=JSON.parse(JSON.stringify(db));const {createDailyDictationController}=await app();const restored=createDailyDictationController({getDB:()=>raw,getWords:()=>[cat],now:()=>100000,persist:()=>true});assert.equal(restored.state().paused,true);restored.resume();spell(restored,'at');restored.next();assert.deepEqual(raw.dictationMastered,['cat']);assert.equal(restored.summary().completed,1);});
test('active elapsed excludes background and clockis injectable',async()=>{const {c,advance}=await setup([cat]);c.start({mode:'dictation',unit:1});advance(6000);c.pause();advance(100000);assert.equal(c.summary().elapsedMs,6000);c.resume();advance(2000);c.pause();assert.equal(c.summary().elapsedMs,8000);});
test('15minutecheckpoint offers finish, never credits remaining words',async()=>{const {c,advance,db}=await setup([cat,dog]);c.start({mode:'dictation',unit:1});advance(900001);c.checkTime();assert.equal(c.state().paused,true);assert.equal(c.state().pauseReason,'time-budget');c.finish();assert.equal(c.state().phase,'completed');assert.equal(c.summary().completed,0);assert.equal(c.summary().planned,2);assert.equal(c.summary().reason,'time-budget');assert.deepEqual(db.dictationMastered,[]);});
test('earlyfinish keepscompleted facts and unfinished words priority nexttime',async()=>{const {c,db}=await setup([cat,dog]);c.start({mode:'dictation',unit:1});warm(c,[cat,dog]);spell(c,'cat');c.finish();assert.deepEqual(db.dictationMastered,['cat']);assert.equal(c.summary().completed,1);c.start({mode:'dictation',unit:1});assert.equal(c.state().words[0].w,'dog');});
test('customparser imported listpersists and invalid lines explained',async()=>{const {c,db}=await setup();const x=c.importWords('cat 猫\nwrong\nlook after 照顾');assert.equal(x.bad,1);assert.equal(db.custom.length,2);assert.equal(c.start({mode:'dictation',unit:0}),true);assert.equal(c.state().words.length,2);});
test('customphrase punctuation formal exactspelling, warmup letters only',async()=>{const {c,db}=await setup([phrase]);c.start({mode:'dictation',unit:1});warm(c,[phrase]);spell(c,phrase.w);c.next();assert.deepEqual(db.dictationMastered,[phrase.w]);});
test('unknown fields and freerun snapshot survive every daily mutation',async()=>{const {c,db}=await setup([cat]);db.activeRun={future:'unknown'};c.start({mode:'dictation',unit:1});warm(c,[cat]);spell(c,'cat');c.next();assert.deepEqual(db.activeRun,{future:'unknown'});assert.deepEqual(db.future,{keep:1});});
test('persist false does not claim successfulsave',async()=>{const {c}=await setup([cat],{persist:()=>false});c.start({mode:'dictation',unit:1});assert.equal(c.saved(),false);c.pause();assert.equal(c.saved(),false);});
test('future/corrupt daily snapshot failclosed and never overwritten',async()=>{const {createDailyDictationController}=await app();for(const raw of [{schemaVersion:999},{schemaVersion:1,phase:'formal',words:[]}]){const db={dailySession:raw};let saves=0;const c=createDailyDictationController({getDB:()=>db,getWords:()=>[cat],persist:()=>{saves++;return true}});assert.equal(c.state(),null);assert.equal(c.start({mode:'dictation',unit:1}),false);assert.equal(saves,0);assert.equal(db.dailySession,raw);}});
test('completion callbacks areexactlyonce across doubles andrefresh',async()=>{let completed=0,attempts=0;const {c,db}=await setup([cat],{onComplete:()=>completed++,onAttempt:()=>attempts++});c.start({mode:'dictation',unit:1});warm(c,[cat]);spell(c,'cat');c.next();c.next();c.finish();assert.equal(completed,1);assert.equal(attempts,1);const {createDailyDictationController}=await app();createDailyDictationController({getDB:()=>JSON.parse(JSON.stringify(db)),getWords:()=>[cat],onComplete:()=>completed++});assert.equal(completed,1);});

test('reviewquota uses actual selected count for tiny lists and manyduewords',async()=>{const {selectDailyWords}=await load();for(const n of [1,2,3]){const words=Array.from({length:n},(_,i)=>({w:'school'+i,z:'今日'}));const dueWords=Array.from({length:12},(_,i)=>({w:'due'+i,z:'复习'}));for(const due of [dueWords,[...words,...dueWords]]){const x=selectDailyWords({words,dueWords:due});assert.ok(x.reviewCount<=Math.floor(x.words.length/2),JSON.stringify(x));assert.equal(new Set(x.words.map(x=>x.w)).size,x.words.length);assert.ok(x.words.some(w=>w.w.startsWith('school')));}}});

test('timebudget cannotresume anextended15minute dailyround',async()=>{const {c,advance}=await setup([cat]);c.start({mode:'dictation',unit:1});advance(900001);c.checkTime();assert.equal(c.resume(),false);assert.equal(c.state().paused,true);});
test('partial wrong orhintword appearsin honestsummary without inflatedcompleted',async()=>{for(const kind of ['wrong','hint']){const {c}=await setup([cat]);c.start({mode:'dictation',unit:1});warm(c,[cat]);if(kind==='wrong')c.input('a');else c.hint();c.finish();assert.deepEqual(c.summary().wrong,[cat]);assert.equal(c.summary().completed,0);}});
test('wordstart andfailure ports runbefore actualsave withpartial formal evidence',async()=>{const events=[];const {c}=await setup([cat],{onWordStart:e=>events.push('word:'+e.attempt.phase),onFailure:e=>events.push('failure:'+e.word.w),persist:()=>{events.push('save');return true}});c.start({mode:'dictation',unit:1});warm(c,[cat]);events.length=0;c.input('a');assert.deepEqual(events,['failure:cat','save']);});
